language: minimal

# not yet testing python installers on osx
# once a set of core installers is defined this matrix should be redrawn
matrix:
    include:
        - os: linux
          python: 2.7
        - os: linux
          python: 3.3
        - os: osx

# Test the install scripts.
script: bash ./install_test.sh
